HUGO ERNESTO CARDENAS ALCARAZ, A03, 23 AGOSTO

# RECORDANDO LISTAS


In [ ]:
Lista = [a,b,c,d,e,f,g]

In [ ]:
# Lista.pop() quita el ultimo
# Lista.pop(2) quita el 3
# Lista.append(x)  agrega al final
# Lista.insert(2,x) inserta x antes del alemento con indice 2

In [17]:
diccionario = {"perro": "animal canino de 3 patas que ldra, es mamifero y tiene cola","gato":"animalfelino de 4 patas que maúlla, es mampifero y tiene cola"}
diccionario
diccionario.keys()

dict_keys(['perro', 'gato'])

In [13]:
gamr = {
    "nombre":"gabirel",
    "apellido":"alvarez",
    "carrera":"psicologia",
    "expediente":744893,
    "materias inscritas": ["mecanica" , "simulacion matematica", "metodos numericos"]
}
josefa = {
    "nombre":"josefa",
    "apellido":"martinez",
    "carrera":"nano",
    "expediente":744844,
    "materias inscritas": ["mecanica", "simulacion matematica", "epicidad matematica", "epicidada mega epica2"]
    
}
alumnosinscritos  = {
    744893 : gamr,
    744844 : josefa
    
}
alumnosinscritos 

{744893: {'nombre': 'gabirel',
  'apellido': 'alvarez',
  'carrera': 'psicologia',
  'expediente': 744893,
  'materias inscritas': ['mecanica',
   'simulacion matematica',
   'metodos numericos']},
 744844: {'nombre': 'josefa',
  'apellido': 'martinez',
  'carrera': 'nano',
  'expediente': 744844,
  'materias inscritas': ['mecanica',
   'simulacion matematica',
   'epicidad matematica',
   'epicidada mega epica2']}}

# LIBRARY

## NUMPY


In [51]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

a


array([1, 2, 3])

In [57]:
c = np.array([[1,2,3]])
c

array([[1, 2, 3]])

In [59]:
d = np.array([[1],[2],[3]])
d

array([[1],
       [2],
       [3]])

In [63]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
c@d

array([[14]])

In [69]:
x=0.5
np.exp(x+2) #e^(x+2)
np.sin(x)
np.cos(x)
np.log10(x)

0.8775825618903728

# PANDAS

In [10]:
import pandas as pd

datos = pd.read_excel("datosPE.xlsx")
datos

ID Persona  Peso  Estatura
0            1    67      1.41
1            2    99      1.83
2            3    86      1.90
3            4   118      1.65
4            5   109      1.67
..         ...   ...       ...
95          96    88      1.49
96          97    98      1.54
97          98    95      1.57
98          99    61      1.61
99         100   107      1.62

[100 rows x 3 columns]

In [16]:
datos.shape

(100, 3)

# EJERCICIO

In [39]:
finanzas = pd.read_excel("datosCT.xlsx")
fin = pd.DataFrame(finanzas)
fin

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

In [122]:
#utilidad
fin.columns
ingresos = fin["Ingreso"] 
ingresos.sum()


28020

In [76]:
fin.sum()

Unnamed: 0    EneroFebreroMarzoAbrilMayoJunioJulioAgostoSept...
Ingreso                                                   28020
Gasto                                                     27710
dtype: object

In [120]:
gastos = fin["Gasto"]
gastos.sum()

27710

In [126]:
Utilidades = ingresos.sum() - gastos.sum()
Utilidades

310

In [140]:
import numpy as np
A = np.array([[1,2],[3,4]])
b = np.array([[2],[4]])
b


array([[2],
       [4]])

array([[1, 2],
       [3, 4]])