# 1

1.- Un proyecto de construcción está por comenzar. Se hace la compra de los materiales y el proveedor dice que en promedio tardan una semana con una desviación de 3 días en llegar. Una vez llegados los materiales se tarda entre 3 y 5 semanas en construir (uniforme). Después de la construcción se deben esperar 3 días antes de empezar a pintar, y toma 6 días en promedio con 2 días de desviación estándar hacerlo.

a) Describe en una celda qué distribución usarías para cada paso del proceso

b) Simula cada paso en el proceso un millón de veces

c) Agrupa las simulaciones de cada paso para tener la simulación del proceso completo

d) ¿Cuál es el tiempo promedio para de inicio-fin del proyecto?

e) De acuerdo a tus simulaciones, ¿cuál es el peor caso? ¿cuál es el mejor caso?

f) Si el proyecto se tiene que entregar a más tardar en 50 días o se tiene que pagar una compensación al cliente, ¿cuál es la probabilidad de que el proyecto se entregue a tiempo?

g) ¿Cuál es la probabilidad de que el proyecto tome entre 20 y 40 días?

In [218]:
import numpy as np
import matplotlib.pyplot as plt

#np.random.uniform
#np.random.normal(mu,std,rep)

A)

* Para la primera parte del proceso se debe utilizar una distribución normal
* Para la segunda una distribución uniforme
* Para la tercer de nueva una distribución normal

B)

In [223]:
#b
n = 1000000
compra = np.random.normal(7,3,n)

construir = np.random.uniform(3,5,n)
#contar 3 días de espera antes de pintar
pintar = np.random.normal(6,2,n)
compra,construir,pintar

(array([7.46857109, 5.38502506, 7.11367423, ..., 0.59985683, 9.03802577,
        6.64164834]),
 array([3.99228675, 3.71134306, 3.9805697 , ..., 4.36456518, 3.76223599,
        4.26718617]),
 array([7.10546379, 4.71881016, 9.02837038, ..., 7.11300343, 8.06775823,
        9.26100365]))

C)

In [263]:
def obra (n):
    compra = np.random.normal(7,3,n)
    construir = np.random.uniform(3,5,n)
    dias_extra = 3
    pintar = np.random.normal(6,2,n)
    return compra +construir + pintar + dias_extra
obra(n)

array([24.07993372, 20.05159912, 16.15451721, ..., 19.93356234,
       21.56531179, 16.42888865])

D)

**Días promedio**

In [266]:
obra(n).mean()

20.001131479154036

E)

**MIN**

In [255]:
# min
obra(n).min()

0.554436148206368

**MAX**

In [259]:
obra(n).max()

38.9545020651235

F)

In [270]:
menos_de_cinc = (np.array(obra(n)) <= 50)
menos_de_cinc.mean()

1.0

**PROBABILIDAD = 100%**

In [272]:
rango = (np.array(obra(n)) > 20) & (np.array(obra(n)) < 40)
rango.mean()

0.500757

# 2

2.- Hay un elevador pequeño en una plaza donde se espera que entren máximo 4 personas a la vez, y su capacidad de peso para poder operar es de 300 kg. En el último censo se encontró que habían 378350 personas en la zona:

* 185392 mujeres
* 162690 hombres
* 30268 personas que o prefirieron no dar la información o se identificaron como no binarias


El peso promedio medido en mujeres es de 70 kg con una desviación estándar de 11 kg. En los hombres se midió un peso promedio de 80 kg y una desviación estándar de 16 kg. En el tercer grupo se midió un peso promedio de 73 kg con una desviación estándar de 12 kg.

a) Si el elevador se llenara 10,000 veces, ¿cuántas de esas veces se excedería el peso permitido?

b) ¿Qué peso total tendría que soportar el elevador si se quiere que el 95% de las veces que se llene no se exceda el peso permitido?

In [292]:
mujeres = np.random.normal(70,11,n)
hombres = np.random.normal(80,16,n)
non_bin = np.random.normal(73,12,n)


A)

In [380]:
n2 = 10000
def elevador(n):
    mujeres = np.random.normal(70,11,n)
    hombres = np.random.normal(80,16,n)
    non_bin = np.random.normal(73,12,n)
    return mujeres + hombres + non_bin
a = (np.array(elevador(n2)) >=300).sum()
a

7

B)

In [433]:
b = elevador(n2) < 261
b.mean()

0.9508

**Para el 95%, debería ser 261kg**

# 3

3. Tienes diez dados justos. Si arrojas todos al mismo tiempo, ¿cuál es la probabilidad de que la suma de los dados sea múltiplo de 6?

In [506]:
n = 100000

def dados(n):
    d1 = np.random.randint(1,7,n)
    d2 = np.random.randint(1,7,n)
    d3 = np.random.randint(1,7,n)
    d4 = np.random.randint(1,7,n)
    d5 = np.random.randint(1,7,n)
    d6 = np.random.randint(1,7,n)
    d7 = np.random.randint(1,7,n)
    d8 = np.random.randint(1,7,n)
    d9 = np.random.randint(1,7,n)
    d10 =np.random.randint(1,7,n)
    suma = d1+d2+d3+d4+d5+d6+d7+d8+d9+d10
    return suma
exito = dados(n)%6 == 0

exito.mean()

0.16692

# 4

A y B juegan al siguiente juego: un número k del 1 al 6 es elegido, y A y B avientan el dado por turnos hasta que alguien consiga que el dado caiga en k. El ganador recibe $100.

a) ¿Cuál es la probabilidad de que el primer jugador gane?

b) ¿Cuál es la probabilidad de que el segundo jugador gane?

c) ¿Cuánto vale la pena pagar para ir primero?

In [488]:
def juego():
    numero = np.random.randint(1,7)
    tiroA = 0
    tiroB = 0
    while numero != tiroA and numero != tiroB:
        tiroA = np.random.randint(1,7)
        tiroB = np.random.randint(1,7)
        if tiroA == numero:
            return "A"
        if tiroB == numero:
            return "B"
juego()

'A'

In [490]:
def proba_A(n):
    TOTALES = []
    for i in range(n):
        games = juego()
        TOTALES.append(games)
    mean = (np.array(TOTALES) == "A").mean()
    return mean


In [492]:
proba_A(n2)

0.543

In [494]:
def proba_B(n):
    TOTALES = []
    for i in range(n):
        games = juego()
        TOTALES.append(games)
    mean = (np.array(TOTALES) == "B").mean()
    return mean 

In [496]:
proba_B(n2)

0.4559

In [514]:
""" Si ganará eñ 0.54 y el otro el 0.46. Vale la pena pagar la diferencia que se tiene con el primero de un total de 100, ya que son consideradas
tiradas individuales por lo que sería (diferencia*100)"""
prob_dif= proba_A(n2)-proba_B(n2)
prob_dif

0.09129999999999999

In [516]:
prob_dif*100

9.129999999999999