HUGO ERNESTO CARDENAS ALCARAZ 744893, 14-11-24

# Laboratorio: Métodos de búsqueda

En las clases anteriores creaste códigos para realizar búsquedas aleatorias (Simulated Annealing) y búsquedas dirigidas (Optimización Bayesiana). Estos métodos de búsqueda se utilizan para facilitar el proceso de optimización de funciones objetivos compleja y costosas de computar.

En este laboratorio usaremos el dataset de los diferentes tipos de iris, y sus longitudes y anchos de pétalos y sépalos. Utilizaremos un RandomForest para crear un modelo de clasificación y el métrico F1 para decidir cuál es el mejor modelo de acuerdo a lo que tenemos disponible.

1. Carga el dataset de Iris

In [331]:
from sklearn import datasets
X, y = datasets.load_iris(return_X_y=True)

X.shape


(150, 4)

2. Importa el archivo `Bosque.py`.

Este archivo contiene la función `RegresionBosque`, que recibe:
- X: las características independientes
- y: la variable de respuesta
- árboles: cantidad total de árboles
- profundidad de bosque: niveles de profundidad del bosque

Su salida es:
- modelo: El objeto con el modelo ajustado
- f1: El métrico que califica qué tan bueno es el modelo que se ajustó.


In [160]:
import Bosque
modelo, f1 = Bosque.RegresionBosque(X, y, 10, 3)
f1

0.9555555555555556

### Actividad 1:

Inicializa un espacio con 5 muestras en nuestro dominio de variables independientes:
- árboles: números enteros entre 5 y 50.
- profundidad: números enteros entre 2 y 10

Utiliza optimización Bayesiana para encontrar la combinación de árboles y profundidad que **maximice** el métrico F1.

In [290]:
import numpy as np
import matplotlib.pyplot as plt
arboles = np.random.randint(5,51,5)
tree = arboles.reshape([-1,1])
profundidad = np.random.randint(2,11,5)
depth = profundidad.reshape([-1,1])
tree,depth
modelo_1,uno = Bosque.RegresionBosque(X, y, arboles[0], profundidad[0])
modelo_2,dos = Bosque.RegresionBosque(X, y, arboles[1], profundidad[1])
modelo_3,tres = Bosque.RegresionBosque(X, y, arboles[2], profundidad[2])
modelo_4,cuatro = Bosque.RegresionBosque(X, y, arboles[3], profundidad[3])
modelo_5,cinco = Bosque.RegresionBosque(X, y, arboles[4], profundidad[4])
#modelo_6,seis = Bosque.RegresionBosque(X, y, 50, 10)
valores_z = np.array([uno,dos,tres,cuatro,cinco])
valores_z

array([0.95555556, 0.93333333, 0.94444444, 0.93333333, 0.95555556])

In [292]:
x_profundidad[i_next]

array([6.86886887])

In [311]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
X_hyper = np.hstack((tree, depth))
valores_z = np.array([uno,dos,tres,cuatro,cinco])
n = 10
NEWX = []
kernel = 1.0*RBF(length_scale = 1)
for i in range(n):
    gp = GaussianProcessRegressor(kernel = kernel, n_restarts_optimizer = 10).fit(X_hyper,valores_z)
    
    x_tree = np.linspace(5,50,1000).reshape([-1,1])
    x_profundidad = np.linspace(2,10,1000).reshape([-1,1])
    x_hyper = np.hstack((x_tree, x_profundidad))
    y_pred, y_std = gp.predict(x_hyper, return_std = True)
    
    #y_pred_low = y_pred - 1.96*(y_std)
    y_pred_high = y_pred + 1.96*(y_std)
    
    i_next = np.argmax(y_pred_high)
    X_hyper = np.vstack((X_hyper,x_hyper[i_next]))
    modelo, valores_z1 = Bosque.RegresionBosque(X, y, int(x_tree[i_next][0]), int(x_profundidad[i_next][0]))
    valores_z = np.hstack((valores_z, valores_z1))

    

C:\Users\hugoc\anaconda3\Lib\site-packages\sklearn\gaussian_process\_gpr.py:663: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)


In [312]:
X_hyper

array([[18.        ,  3.        ],
       [ 8.        ,  2.        ],
       [ 6.        ,  7.        ],
       [17.        ,  2.        ],
       [35.        , 10.        ],
       [27.7027027 ,  6.03603604],
       [19.86486486,  4.64264264],
       [47.7027027 ,  9.59159159],
       [39.77477477,  8.18218218],
       [12.65765766,  3.36136136],
       [50.        , 10.        ],
       [33.69369369,  7.1011011 ],
       [ 9.45945946,  2.79279279],
       [ 5.        ,  2.        ],
       [43.87387387,  8.91091091]])

In [333]:
valores_z.max()

0.9555555555555556

MAX : 0.95555555

### Actividad 2:

Inicializa 2 vectores con posibles valores para las variables independientes:
- árboles: números enteros entre 5 y 50
- profundidad: números enteros entre 2 y 10

Utiliza el algoritmo de Simulated Annealing que siga el siguiente orden:
- Elige un punto de partida para las variables.
- Selecciona al azar una de las dos para modificarlas.
- Selecciona un elemento al azar de la lista que contiene los posibles valores de esa variable.
- Sigue el algoritmo ($p$ y $q$) para decidir si usas esa combinación nueva o si mantienes la anterior.

In [391]:
trees = []
for i in range(46):
    x = i+5
    trees.append(x)
arb = (np.array(trees)).reshape([-1,1])
prof = np.array([2,3,4,5,6,7,8,9,10]).reshape([-1,1])


##### Se utilizó T=1 debido a que el tiempo de computación mayor a 1, era excesivo, realmente nunca supe cuanto tardaba, no tuve el tiempo para comprobarlo.

In [405]:
T  = 1
def vectorX():
    
    var1 = arb[np.random.randint(45)]
    var2 = prof[np.random.randint(9)]
    
    vector = np.array([var1[0],var2[0]])
    return vector 
vector = vectorX()
vector

array([38,  3])

In [407]:
def act2_1(vec):
   
    vector = vec
    vector2 = vector.copy()
    choice1 = np.random.choice([0,1])
    if choice1 == 0:
        rand_var = arb[np.random.randint(45)]
        vector2[0] = rand_var[0]
    else:
        rand_var = prof[np.random.randint(9)]
        vector2[1] = rand_var[0]
    
    _,d1 = Bosque.RegresionBosque(X, y, vector[0], vector[1])
    _,d2 = Bosque.RegresionBosque(X, y, vector2[0], vector2[1])
    #seguir procedimiento p - q 
    def valor_p(d1,d2,T):
        return np.exp((d1-d2)/T)
    q = valor_p(d1,d2,T)
    p = np.random.rand()*1.4
    if p < q :
        ELEGIDO = vector2
    else:
        ELEGIDO = vector
    return ELEGIDO
    

act2_1(vector)

array([37,  3])

In [408]:
def act2_2(vec,N):
    
    for i in range(N):
        vec = act2_1(vec)
    return vec

act2_2(vector,1)

array([38, 10])

In [409]:
def act2_3(T,N):
    vector = vectorX()
    while T > 1:
        for i in range(N):
            vector = act2_2(vector,N)
            T = T*0.9
    return vector
            

act2_3(T,1)

array([38,  4])

In [413]:
M = 4
N = 4

In [415]:
def act2_4(T,M,N):
    f1y = []
    Mod = []
    m = 0
    while m < M:
        for i in range(N):
            vec = act2_3(T,N)
            x,f1x = Bosque.RegresionBosque(X, y, vector[0], vector[1])
            m +=1
            Mod.append(vector)
            f1y.append(f1x)
    return f1y,Mod
        
        
f1_n,Mod = act2_4(T,M,N)  


In [417]:
(np.array(f1_n)).max()

0.9555555555555556

MAX : 0.9555555